### ISSUE TITLE
Gem not available on rubygems.org

### ISSUE THREAD

**Issue by stuffandthings** [patricklindsay/simple_form-materialize#1]
Hey, I can't install the gem from rubygems.org, just curious if you removed it for any reason/it was never added?

**Comment by patricklindsay** [comment]
I haven't released the gem yet as I'm stuck trying to port the materialize custom widgets into the gem. Check [this issue](https://github.com/patricklindsay/simple_form-materialize/issues/2) for further details. I could release a 0.0.1 version with just the config if people wanted.

**Comment by stuffandthings** [comment]
I'm going to go ahead and close this issue then. I'll take a crack at that issue if I find some time, thanks for the response!
